name: bs
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prerequisites
        run: |
          sudo apt-get install pipx
          pipx install bikeshed
      - name: render
        run: |
          changes=$(git diff --name-only HEAD HEAD~1 | grep -E "(c/|cpp/)" | cat)
          for path in c cpp;
          do
            cd $path
            for f in *.bs;
            do
              if [[ $changes =~ "$path/$f" ]];
              then
                bikeshed spec $f
              fi
            done
            cd ..
          done
      - name: upload renders
        run: |
          message=$(git show -s --format=%s)
          mkdir /tmp/renders
          for path in c cpp;
          do
            mkdir /tmp/renders/$path
            if compgen -G "$path/*.html" > /dev/null; then
              mv -v $path/*.html /tmp/renders/$path
            fi
          done
          git checkout gh-pages
          for path in c cpp;
          do
            if compgen -G "/tmp/renders/$path/*" > /dev/null; then
              mkdir -p $path
              mv -v /tmp/renders/$path/* $path
            fi
          done
          rm -rfv drafts
          git checkout main -- drafts
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [[ -n "$(git status -s)" ]];
          then
            git add .
            git commit -m "[Bikeshed]: $message"
            git push
          fi
